apiVersion: v1
kind: PersistentVolume
metadata:
  name: avocado-pv
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/node01/webapp_templates/avocado/dist"

