apiVersion: v1
kind: PersistentVolume
metadata:
  name: shop-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/node01/webapp_templates/shop/html"
