apiVersion: v1
data:
  http.conf: |
    server {
            listen 80;
            server_name test.sharqa.com;
            root /www/;
            index index.html;
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: http-conf
