apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: avocado
  name: avocado-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32142
  selector:
    app: avocado
  type: NodePort
status:
  loadBalancer: {}
