pipeline {
    agent any
    
    environment {
        COMPONENT = 'nginx'
    }    

    stages {
        stage('Checkout') {
            steps {
              sh 'echo ${COMPONENT}'
              checkout([$class: 'GitSCM', 
                branches: [[name: '*/main']],
                extensions: [
                    [$class: 'SparseCheckoutPaths', 
                    sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path:'/fullstack/env.COMPONENT']]]
                    ],
                userRemoteConfigs: [[url: 'https://github.com/MohammadB88/webapp.git']]])
              sh "ls -ltr"
          }
        }

        stage('build image') {
      	  steps {
	          script {
              sh "pwd"
              dir('fullstack/env.COMPONENT') {
                  sh "pwd"
                  sh 'ls -la'
                  sh 'docker build -t "mohammad67/bookreview_${COMPONENT}:${BUILD_NUMBER}" . '
                  sh 'docker build -t "mohammad67/bookreview_${COMPONENT}:latest" . '
              }
              sh "pwd"
	          }
	        }
        }

        stage('test') {
	        steps {
           sh 'echo Hello from Test Section'
	        }
        }

        stage('push image') {
	        steps {
            script {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pass', usernameVariable: 'user')]){
                    sh 'docker login -u$user -p$pass'
                    sh 'docker push mohammad67/bookreview_${COMPONENT}:${BUILD_NUMBER}'
                    sh 'docker push mohammad67/bookreview_${COMPONENT}:latest'
                }
        	    }
	          }
	      }
        
        stage('trigger updatemanifestjob"') {
          steps {
            sh 'echo "triggering updatemanifestjob"'
            build job: 'updatemanifest', parameters: [
              string(name: 'DOCKERTAG', value: env.BUILD_NUMBER),
              string(name: 'COMPONENT', value: '${COMPONENT}')
            ]            
          }
        }
    }
}
