apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: mysql-db-svc
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1m"
              memory: "25Mi"
            limits:
              cpu: "5m"
              memory: "50Mi"
