apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: books
            - name: MYSQL_HOST_IP
              value: mysql-db-svc
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          image: mohammad67/bookreview_backend:latest
          name: backend
          imagePullPolicy: Always
          ports:
          - containerPort: 3001
