apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mohammad67/bookreview_backend:14
          env:
            - name: MYSQL_DATABASE
              value: book_reviews
            - name: MYSQL_HOST_IP
              value: mysql-db-svc
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          imagePullPolicy: Always
          ports:
          - containerPort: 3001
          resources:
            requests:
              cpu: "1m"
              memory: "35Mi"
            limits:
              cpu: "5m"
              memory: "70Mi"
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
