apiVersion: v1
data:
  setup.sql: |
    CREATE DATABASE IF NOT EXISTS book_reviews;
    USE book_reviews;

    CREATE TABLE reviews (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      author VARCHAR(255) NOT NULL,
      rating INT NOT NULL,
      review TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: database-init-script