apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-proxy
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - image: mohammad67/bookreview_nginx
          name: nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
