apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: static
    name: static
spec:
    replicas: 2
    selector:
        matchLabels:
            app: static
    template:
      metadata:
        labels:
          app: static
      spec:
        containers:
          - image: mohammad67/nginx-static-weave:v1.0
            imagePullPolicy: IfNotPresent
            name: static
            volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
        volumes:
        - name: config-volume
          configMap:
            name: app-config
