apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - env:
            - name: ADMINER_DEFAULT_SERVER
              value: mysql-db-svc
          image: adminer:latest
          name: adminer
          ports:
            - containerPort: 8080
