apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: adminer
  strategy: {}
  template:
    metadata:
      labels:
        name: adminer
    spec:
      containers:
        - env:
            - name: ADMINER_DEFAULT_SERVER
              value: mysql-db-svc
          image: adminer:latest
          name: adminer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
