apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-svc
  name: api-svc
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    name: api
status:
  loadBalancer: {}
