apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: books
            - name: MYSQL_HOST_IP
              value: mysql-db-svc
            - name: MYSQL_PASSWORD
              value: MYSQL_PASSWORD
            - name: MYSQL_USER
              value: MYSQL_USER
          image: mohammad67/mosesreigns_apiserver:v1.1
          name: api
          imagePullPolicy: Always
          ports:
          - containerPort: 3001
