apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: api-svc
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: backend
status:
  loadBalancer: {}
