apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: client
    spec:
      containers:
        - image: mohammad67/mosesreigns_client:v1.0
          name: client
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          #      volumeMounts:
          #  - mountPath: /app
          #    name: client-claim
          #restartPolicy: Always
          #volumes:
          # - name: client-claim
          #persistentVolumeClaim:
          #claimName: client-pvc
