apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: mohammad67/mosesreigns_client:v1.0
          name: client
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
