apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mysql-db-pvc
  name: mysql-db-pvc
spec:
  storageClassName: local-storage
  volumeName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
