apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: books
            - name: MYSQL_HOST
              value: localhost
            - name: MYSQL_USER
              value: MYSQL_USER
            - name: MYSQL_PASSWORD
              value: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              value: MYSQL_ROOT_PASSWORD
          image: mysql
          name: mysql-db
          ports:
          - containerPort: 3306
          resources: {}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-script
      volumes:
        - name: mysql-script
          configMap:
            name: database-init-script
