apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  strategy: {}
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - image: mohammad67/mosesreigns_nginx:v1.0
          name: nginx
          ports:
          - containerPort: 80
