apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-svc
  name: nginx-svc
spec:
  ports:
    - name: "3050"
      port: 3050
      targetPort: 80
  selector:
    name: nginx
status:
  loadBalancer: {}
