node {
    stage('Clone repository') {
        checkout([$class: 'GitSCM', 
        branches: [[name: '*/main']],
        extensions: [
            [$class: 'SparseCheckoutPaths', 
            sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path:'/fullstack/nginx']]]
            ],
        userRemoteConfigs: [[url: 'https://github.com/MohammadB88/webapp.git']]])
        sh "ls -ltr"
    }
    stage('build image') {
        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
            def app = docker.build("mohammad67/test:${env.BUILD_NUMBER}", "./fullstack/nginx")
            app.push() 
        }
    }
    stage('test') {
            sh 'echo Hello from Test Section'
    }
    stage('deploy') {
            sh 'echo Hello from Deploy Section'
    }
}


