pipeline {
    agent any
    def docker_loc = tool 'mydocker'
    stages {
        stage('Checkout') {
            steps {
              checkout([$class: 'GitSCM', 
                branches: [[name: '*/main']],
                extensions: [
                    [$class: 'SparseCheckoutPaths', 
                    sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path:'/jenkins/script']]]
                    ],
                userRemoteConfigs: [[url: 'https://github.com/naiveskill/devops.git']]])
              sh "ls -ltr"
          }
        }
        stage('build image') {
      	  steps {
	          script {
	             sh "${docker_loc}/mydocker build -t mohammad67/test:${BUILD_NUMBER} -f ./fullstack/nginx .")
	          }
	        }
        }
        stage('test') {
	        steps {
           sh 'echo Hello from Test Section'
	        }
        }
        stage('push image') {
	        steps {
            script {
	   	        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
	        	    docker_image.push("mohammad67/test:${BUILD_NUMBER}") 
        	    }
	          }
	        }
        }
        stage('deploy') {
          steps {
            sh 'echo Hello from Deploy Section'
          }
        }
    }
}
