apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shop
  name: shop-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32143
  selector:
    app: shop
  type: NodePort
status:
  loadBalancer: {}
