pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
              checkout([$class: 'GitSCM', 
                branches: [[name: '*/main']],
                extensions: [
                    [$class: 'SparseCheckoutPaths', 
                    sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path:'/fullstack/backend']]]
                    ],
                userRemoteConfigs: [[url: 'https://github.com/MohammadB88/webapp.git']]])
              sh "ls -ltr"
          }
        }

        stage('Build') {
            agent {
                docker {
                    image 'gradle:6.7-jdk11'
                    // Run the container on the node specified at the
                    // top-level of the Pipeline, in the same workspace,
                    // rather than on a new node entirely:
                    reuseNode true
                }
            }
            steps {
                sh 'gradle --version'
            }
        }
        
        stage('build image') {
      	  steps {
	          script {
              sh "pwd"
              dir('fullstack/backend') {
                  sh "pwd"
                  sh 'ls -la'
                  sh 'docker build -t "mohammad67/bookreview_backend:${BUILD_NUMBER}" . '
                  sh 'docker build -t "mohammad67/bookreview_backend:latest" . '
              }
              sh "pwd"
	          }
	        }
        }

        stage('test') {
	        steps {
           sh 'echo Hello from Test Section'
	        }
        }

        stage('push image') {
	        steps {
            script {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pass', usernameVariable: 'user')]){
                    sh 'docker login -u$user -p$pass'
                    sh 'docker push mohammad67/bookreview_backend:${BUILD_NUMBER}'
                    sh 'docker push mohammad67/bookreview_backend:latest'
                }
        	    }
	          }
	      }
        
        stage('trigger updatemanifestjob"') {
          steps {
            sh 'echo "triggering updatemanifestjob"'
            build job: 'updatemanifest', parameters: [
              string(name: 'DOCKERTAG', value: env.BUILD_NUMBER),
              string(name: 'COMPONENT', value: 'backend')
            ]            
          }
        }
    }
}
