name: Build and Test Docker Image

env:
  IMAGE_TAG: "latest"

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./fullstack/backend
        file: ./fullstack/backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend:${{ env.IMAGE_TAG }}
    -
      name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./fullstack/frontent
        file: ./fullstack/frontent/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookreview_frontent:${{ env.IMAGE_TAG }}
