name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./fullstack/backend
        file: ./fullstack/backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend:ga
    - 
      name: update the manifest for backend apps
      run: |
        sh "sed -i 's+mohammad67/bookreview_backend.*+mohammad67/bookreview_backend:ga+g' fullstack/backend-deployment.yml"

      # uses: jacobtomlinson/gha-find-replace@v2
      # with:
      #   find: "${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend:1"
      #   replace: "${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend:ga"
      #   regex: false
      #   include: ./fullstack/backend-deployment.yml
    - 
      name: Commit and push changes
      run: |
        git config --global user.name "${{ secrets.G_USERNAME }}"
        git config --global user.email "${{ secrets.G_EMAIL }}"

        git add -A
        git commit -m "commit message"
        git push
