name: Update Kubernetes Manifests

on:
  workflow_run:
    workflows: [Build and Test Docker Image]
    types: [completed]

jobs:

  update_manifests:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: update the manifest for backend apps
      working-directory: ./fullstack
      run: |
        pwd
        ls -la
        cat backend-deployment.yml
        sed -i 's+${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend.*+${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend:${{ env.IMAGE_TAG }}+g' backend-deployment.yml

    - 
      name: update the manifest for frontend apps
      working-directory: ./fullstack
      run: |
        pwd
        ls -la
        cat frontend-deployment.yml
        sed -i 's+${{ secrets.DOCKERHUB_USERNAME }}/bookreview_frontend.*+${{ secrets.DOCKERHUB_USERNAME }}/bookreview_frontend:${{ env.IMAGE_TAG }}+g' frontend-deployment.yml

      # uses: jacobtomlinson/gha-find-replace@v2
      # with:
      #   find: "${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend:1"
      #   replace: "${{ secrets.DOCKERHUB_USERNAME }}/bookreview_backend:ga"
      #   regex: false
      #   include: ./fullstack/backend-deployment.yml
  
  deploy-changes:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Commit and push changes
      run: |
        git config --global user.name "${{ secrets.G_USERNAME }}"
        git config --global user.email "${{ secrets.G_EMAIL }}"

        git add -A
        git commit -m "commit message"
        git push
